# Dependencies
markdown:             kramdown
highlighter:          rouge

# Permalinks
permalink:            pretty

# Setup
title:                Luca Pierabella
tagline:              My personal blog
description:          A blog about technical art, personal work and often just a notebook to share
url:                  https://elpie89.github.io/
baseurl:
paginate:             5
name:                 Luca Pierabella

gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist

# SEO
# twitter:
#   username:           fredrikaverpil
#   url:                https://twitter.com/fredrikaverpil
social:
  name:               Luca Pierabella
  links:
    - https://www.linkedin.com/in/luca-pierabella-93308413
    - https://www.facebook.com/luca.pierabella
    - https://github.com/elpie89

# Custom vars
custom_pages:
  feed:               /atom.xml
github:
    url:              https://github.com/elpie89
    repo:             https://github.com/elpie89/elpie89.github.io
    
excerpt_separator:    <!--more-->
google_analytics:     UA-70773524-1
hyde_version:         2.1.0
hyde_url:             http://hyde.getpoole.com
hyde_repo:            https://github.com/poole/hyde
show_related_posts:   false
force_https:          true

# Comments
comments:
  use_disqus:         true
  use_googleplus:     false
  disqus_shortname:   elpie89

# Custom template for special page 
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

repository:	elpie89/elpie89.github.io
